### PR TITLE
feat: add catch-all support

### LINKED ISSUE #17: Add support for catch-all route
First of all, thank you for this package.

In Nuxt 3, there is support for [catch-all routes](https://v3.nuxtjs.org/guide/directory-structure/pages/#catch-all-route). This is useful when one wants to catch routes with a variable depth, for instance `/path/to/file` and `/path/to/a/deeply/nested/file` would be both captured by a file named `/path/to/[...path].js`.

Could express-file-routing have support for these catch-all routes?

### PR DESCRIPTION
**Pull request by NotaRobot13**
you can now make a new catch-all route by making a folder called `[$]`. see the example written in the readme. this also solves #17

### CODE REVIEW

**Comment by matthiaaas** [comment]
hey @NotaRobot13, thank you for your contribution to the issue #17. Unfortunately, the catch-all doesn't work for me in my local environment.

Here's the code:
```js
// app.js
const express = require("express")
const { router } = require("../dist")

const app = express()

app.use(router())

app.listen(4000)

// /routes/[$]/index.js
module.exports.get = async (req, res) => {
  return res.send("Hello World!")
}
```

It doesn't match any of the following urls:
- /a
- /a/b/c

**Comment by NotaRobot13** [comment]
@matthiaaas hey, ive quickly uploaded my code as an npm package to demonstrate that it seems to work (don't worry, i'll delete it when you've tested it). furthermore, i've uploaded a sample project to demonstrate that this does seem to work [here](https://github.com/NotaRobot13/catchall-sample-file-routing). if you want to try with your own code, the npm package is `@notarobot13/express-file-routing`. hope this helps!

**Comment by NotaRobot13** [comment]
so, it seems this is in fact a bug in my code. trailing slashes in the requst mess it up. my bad, its because its exact regex. i'll fix it real quick

**Comment by matthiaaas** [comment]
To match with other file-based routers, I did some refactoring and changed the catchall file name syntax.

- `/routes/users/[...catchall].js` matches /users, but also /users/a, /users/a/b and so on.

Further, I think this is a bit less confusing, since the dollar sign ($) is also used as a dynamic parameter prefix (in Express, but also other router solutions).

Let me know what you think @NotaRobot13.

**Comment by NotaRobot13** [comment]
@matthiaaas i was trying to make it easier to type when making a file but that's also a great solution, looks good 👍

**Comment by NotaRobot13** [comment]
@matthiaaas reopening, trailing slashes seems to work but without a trailing slash request fails with 404

**Comment by matthiaaas** [comment]
Can't reproduce. Could you share a minimal code example here in this thread?

**Comment by NotaRobot13** [comment]
@matthiaaas see [here](https://github.com/NotaRobot13/catchall-sample-file-routing), run with provided nodemon config and make request without trailing slash to /catch

**Comment by matthiaaas** [comment]
Yes, you're absolutely right @NotaRobot13. This is because under the current implementation, `/routes/catch/[...catchall].js` is transformed into `/catch/*`, which I expect to be the intended behavior.

Unlike what is stated in the docs, catchall is expected to **only** match dynamic subpaths, **not** the root route itself.
- `/routes/catch/[...catchall].js` matches `/catch/a`, `/catch/a/b` and so on, **but not** `/catch`.

The docs will be updated accordingly to reflect the present implementation.

**Comment by matthiaaas** [comment]
It should be noted that `/routes/catch/[...catchall].js` is expected to match `/catch/`, but not `/catch`. This is a trivial edge case that can be easily fixed by checking `req.params` for an empty string.

Also, this behavior corresponds Express' internal route matching behavior.

**Pull request merged**
